name: Run CI Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  push:
    branches:
      - 'main'
jobs:
  run-tests:
    timeout-minutes: 5
    runs-on: fedora-41
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: go.mod
      - name: Run Go Test
        run: |
          just init tidy lint test
